spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AQAEXsPujFk8XPOMatxLjPdyzRjMCvk94c++RawF/IgsdDdNWZDhr+gJTsA2TrFZyj2qg7533sY6NiTjQSroaWZLjb3NcdX0P1vmF8jUfa8RCCc1P5dpdMgKqkpR37bJoXKUxYKmSVPWiSuNqRMPZPIlRKJ3iCeKESQ+jx0XtfZi8zIoZvSHhY0o21VAunfNywJAQGRvktgZs1TGQdGIfrjwun3hKMEIl1yRtOPLmE0Ay+njVTCQvouNH/NjQ1dMRQFb5EnujHSEV2MF2zdRMHosBZnq4gDJEjdQc2CO8wuN8vT7TLWPUxylAbEOMcKAHXAKkRcVfQR0RBpEBaUEZNXlz91e2DnMzUpewaeuNBCojOv22EPBcwjcF98otU4mREw="

token:
  expiration_time: 86400000
  secret: my_token_dev

gateway:
  ip: 127.0.0.1
