spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AQCQONqS5tKimCJjjNMC9EixWXsWkRvBWTU1ck+fxq3EMghadzw23U0+1QO7yRlntLyI9WH1vwqG66mB9G2CoMbsry/nMzt9VnIWXU3hFjLcU4dItnT13IkV1VDQbMofHK1C0kCh46yHm8G6BXRAg+MCbxTcfPt33l2cyRkG5OEyOnYyp0jFXQq0HlGhQfFaBC7dw7hNh0pDDKzvfKXmoXeicrwRZgHNHZsUoYiRPWaX8DIoXIJolp5yD9ow0FihmnREFlJE/4kbUiUNwAKv6im28KTzIdZPpI1sIOWs6uZtv73q9a4Pro8EXU/CXvZyv9eyUBDUX0GPVGMKgNXqu4vhMUNKEMSYEL84IKh7ypk2i1wX3R7WyWZNaVYurB88v0k="

token:
  expiration_time: 86400000
  secret: "{cipher}AQBAiKU88WJZr/SPJVD2RRjPL6vwGHbZYIB2xqTUTPwdKNXFheRyPvrDsgiPeiTMxkaYKqYJe/jQj2o3t+l8QlEiqN2dGtEBnhGLK4Ue+Gz2WMfRRNF6adt3NeVhqwxrHBMti2tOc6rP1aKbsBCi8SJA+Y2D+6ZopKVGZWiQ1VmJxFopF8yAzyVi/IdrfheG4qkHHZFm5lK8MRdHtOm8OSTmqaLiKohWToYJEjReWlA+u3QoTZLJZwnlylENgytx7ZhBfQPHoZ/DT338KSeyO4dlrDbO8m+yXe8fYOYBDRUialiyyx4pQUIEqn0EeQVAnmaxwsqSPYQsT7C41hiRKq78UeLz7RrL+z62I1haEiodc24bfa976nxayjajnmGXLFo="

gateway:
  ip: 127.0.0.1

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
