spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AQCQONqS5tKimCJjjNMC9EixWXsWkRvBWTU1ck+fxq3EMghadzw23U0+1QO7yRlntLyI9WH1vwqG66mB9G2CoMbsry/nMzt9VnIWXU3hFjLcU4dItnT13IkV1VDQbMofHK1C0kCh46yHm8G6BXRAg+MCbxTcfPt33l2cyRkG5OEyOnYyp0jFXQq0HlGhQfFaBC7dw7hNh0pDDKzvfKXmoXeicrwRZgHNHZsUoYiRPWaX8DIoXIJolp5yD9ow0FihmnREFlJE/4kbUiUNwAKv6im28KTzIdZPpI1sIOWs6uZtv73q9a4Pro8EXU/CXvZyv9eyUBDUX0GPVGMKgNXqu4vhMUNKEMSYEL84IKh7ypk2i1wX3R7WyWZNaVYurB88v0k="

token:
  expiration_time: 86400000
  secret: my_token_dev

gateway:
  ip: 127.0.0.1
